namespace Business.Helpers
{
    public class DateValidationHelper
    {
        // Date validation methods generated by ChatGPT
        public static bool IsValidDate(string dateInput)
        {
            return DateTime.TryParseExact(
                dateInput,
                "yyyy-MM-dd",
                null,
                System.Globalization.DateTimeStyles.None,
                out _
            );
        }

        // Checks if a date is today or in the future
        public static bool IsFutureOrTodayDate(DateTime date)
        {
            return date >= DateTime.Now.Date; // Use .Date to ignore the time component
        }

        // Validates that the end date is after the start date
        public static bool IsEndDateAfterStartDate(DateTime? startDate, DateTime? endDate)
        {
            return !endDate.HasValue || (startDate.HasValue && endDate.Value >= startDate.Value);
        }
    }
}
