using System.Text.RegularExpressions;

namespace Business.Helpers
{
    public class EmailValidationHelper
    {
        // Regular expression generated by CHatGPT to validate email addresses.
        public static bool IsValidEmail(string email)
        {
            var emailPattern = @"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$";
            return Regex.IsMatch(email, emailPattern);
        }
    }
}
