using System.Text.RegularExpressions;

namespace Business.Helpers
{
    public static class PhoneValidationHelper
    {
        // Regular expression generated by ChatGPT to validate phone numbers.
        public static bool IsValidPhoneNumber(string phoneNumber)
        {
            // Clean the input to remove spaces, hyphens, and ensure only digits are processed
            phoneNumber = phoneNumber.Replace(" ", "").Replace("-", "");

            // Regular expression to match a Swedish phone number format
            var phonePattern = @"^(?:\+46|0)(7\d{1})\d{7}$";

            return Regex.IsMatch(phoneNumber, phonePattern);
        }
    }
}
