using System.Text.RegularExpressions;

namespace Business.Helpers
{
    public static class PhoneValidationHelper
    {
        // Regular expression generated by CHatGPT to validate phone numbers.
        public static bool IsValidPhoneNumber(string phoneNumber)
        {
            var phonePattern = @"^(\+?\d{1,4}[\s-])?(\(?\d{1,4}\)?[\s-])?(\d{1,4}[\s-]){2}\d{1,4}$";
            return Regex.IsMatch(phoneNumber, phonePattern);
        }
    }
}
