using Microsoft.EntityFrameworkCore;

namespace Business.Helpers
{
    // Helper generated by ChatGPT. It uses a counter to generate the ID for a project and uses a 'P-' prefix for each ID.
    public class ProjectIdGeneratorHelper(DbContext context)
    {
        private readonly DbContext _context =
            context ?? throw new ArgumentNullException(nameof(context));

        public async Task<string> GenerateUniqueProjectIdAsync()
        {
            string prefix = "P-";
            int newIdNumber = 1;

            // Query the most recent project to determine the next available number.
            var lastProject = await _context
                .Set<ProjectEntity>()
                .OrderByDescending(p => p.Id) // Sort by the most recent project.
                .FirstOrDefaultAsync();

            if (lastProject != null)
            {
                // Extract the number from the last project ID (e.g., "P-100" -> 100).
                string lastProjectId = lastProject.Id.ToString();
                if (
                    lastProjectId.StartsWith(prefix)
                    && int.TryParse(lastProjectId[prefix.Length..], out int lastId)
                )
                {
                    newIdNumber = lastId + 1;
                }
            }

            // Generate the new project ID.
            return $"{prefix}{newIdNumber}";
        }
    }
}
